default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost

# development:
#   adapter: mysql2
#   database: your_db_name
#   host: localhost
#   username: your_mysql_user_name
#   password: root's password
#   encoding: utf8

development:
  <<: *default
  database: compose_development